---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-web-app-wbuntu-com-v1-bundle
  failurePolicy: Fail
  name: mbundle.kb.io
  rules:
  - apiGroups:
    - web.app.wbuntu.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bundles
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-web-app-wbuntu-com-v1-bundle
  failurePolicy: Fail
  name: vbundle.kb.io
  rules:
  - apiGroups:
    - web.app.wbuntu.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bundles
  sideEffects: None
