# permissions for end users to edit bundles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bundle-editor-role
rules:
- apiGroups:
  - web.app.wbuntu.com
  resources:
  - bundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.app.wbuntu.com
  resources:
  - bundles/status
  verbs:
  - get
