---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - web.app.wbuntu.com
  resources:
  - bundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.app.wbuntu.com
  resources:
  - bundles/finalizers
  verbs:
  - update
- apiGroups:
  - web.app.wbuntu.com
  resources:
  - bundles/status
  verbs:
  - get
  - patch
  - update
